### ISSUE TITLE
FlowType not working. What am I missing?

### ISSUE THREAD

**Issue by alvarotrigo** [simplefocus/FlowType.JS#47]
As there are no examples available to download I'm not quite sure what I'm missing.

[Here's a reproduction](http://jsfiddle.net/cvfLL40z/) of what I'm trying to do.

What am I missing?

**Comment by jdgraffam** [comment]
You need to include FlowType.js in your JSFiddle.

**Comment by alvarotrigo** [comment]
@jdgraffam it is there. Take a look at the left panel under the `External Resources` section.

**Comment by jdgraffam** [comment]
Sorry, duh. Try this: http://jsfiddle.net/b51h4wcc/

Don't declare font-size on the h2.

**Comment by alvarotrigo** [comment]
Then I assume this lines in the docs are not correct when dealing with px, right?
```css
body {
   font-size: 18px;
}

h1,h2,h3,h4,h5,h6,p {
   line-height: 1.45;
}

h1 { font-size: 4em; }
h2 { font-size: 3em; }
h3 { etc...
```
